### ISSUE TITLE
Manuteção

### ISSUE THREAD

**Issue by mariohmol** [developers-vitta/nodenab#1]
Olá, ainda trabalhando neste projeto?

Estou precisando de algo assim e estou vendo quais repos estao com movimento pra colaborar!

Att,

**Comment by mariohmol** [comment]
O exemplo mesmo esta dando erro =(  

``` 
lote.header.set('codigo_banco', 237);
            ^

TypeError: Cannot read property 'set' of null
```

**Comment by gilsonsouzah** [comment]
Olá Mario, Boa Tarde!

Não estamos mais mantendo esse pacote. Recomendamos o uso do https://www.npmjs.com/package/jsons-to-cnab no lugar.

Grande abraço.

**Comment by mariohmol** [comment]
vlw.. to tocando aq tb https://github.com/mariohmol/nodejs-cnab
